#!/bin/bash

echo "---------------"

echo "ls /autograder/submission/"
ls /autograder/submission/

echo "---------------"

cd /autograder/source
python3 grader.py rubric.json /autograder/submission /autograder/results/results.json