#!/bin/bash

echo "\t---------------"

echo "ls /autograder/"
ls /autograder/

echo "\t---------------"

echo "ls /autograder/source/"
ls /autograder/source/

echo "\t---------------"

echo "ls /autograder/submission/"
ls /autograder/submission/

echo "\t---------------"

cd /autograder/source
python3 grader.py rubric.json /autograder/submission /autograder/results/results.json